package com.example.bandera.entities;

import com.example.bandera.TicketStatus;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;
import java.math.BigDecimal;
import java.time.LocalDateTime;


@Document(collection = "ticket_entity")
public class TicketEntity {

    /* Autogenerated id from phpmyadmin + connecting to the vehicle_entity table via the vehicle_id column + connecting to the customer_entity table via the id column" */
    @Id
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private String id;
    //private VehicleEntity vehicle;
    /* ------------------------ the start of the columns for the ticket_entity --------------------- */
    @JsonFormat(pattern = "yyyy-MM-dd hh:mm a")
    private LocalDateTime dateTime;
    //private String serviceType;
    //private String serviceDetails;
    //private List<PartEntity> partsRequired;

    private List<ServiceEntity> serviceEntity;
    private int laborHours;
    private BigDecimal laborRate;
    private BigDecimal preliminaryCost;
    private TicketStatus ticketStatus;
    @DBRef
    private CustomersEntity customer;

    /* ------------------------ GETTERS && SETTERS --------------------- */



    public String getId() {
        return id;
    }
 /*
    public void setId(String id) {
        this.id = id;
    }
    public VehicleEntity getVehicle() {
        return vehicle;
    }

    public void setVehicle(VehicleEntity vehicle) {
        this.vehicle = vehicle;
    }

     */

    public LocalDateTime getDateTime() {
        return dateTime;
    }

    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }

    public CustomersEntity getCustomer() {
        return customer;
    }

    public void setCustomer(CustomersEntity customer) {
        this.customer = customer;
    }

    /*
    public String getServiceType() {
        return serviceType;
    }

    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }

    public String getServiceDetails() {
        return serviceDetails;
    }

    public void setServiceDetails(String serviceDetails) {
        this.serviceDetails = serviceDetails;
    }

    public List<PartEntity> getPartsRequired() {
        return partsRequired;
    }

    public void setPartsRequired(List<PartEntity> partsRequired) {
        this.partsRequired = partsRequired;
    }

     */

    public List<ServiceEntity> getServiceEntity() {
        return serviceEntity;
    }

    public void setServiceEntity(List<ServiceEntity> serviceEntity) {
        this.serviceEntity = serviceEntity;
    }

    public int getLaborHours() {
        return this.laborHours;
    }

    public void setLaborHours(int laborHours) {
        this.laborHours = laborHours;
    }

    public BigDecimal getLaborRate() {
        return laborRate;
    }

    public void setLaborRate(BigDecimal laborRate) {
        this.laborRate = laborRate;
    }

    public BigDecimal getPreliminaryCost() {
        return preliminaryCost;
    }

    public void setPreliminaryCost(BigDecimal preliminaryCost) {
        this.preliminaryCost = preliminaryCost;
    }

    public TicketStatus getTicketStatus() {
        return ticketStatus;
    }

    public void setTicketStatus(TicketStatus status) {
        this.ticketStatus = status;
    }


}
